### ISSUE TITLE
Example with migration cmdswitch

### ISSUE THREAD

**Issue by profx5015** [ztalbot2000/homebridge-cmd4#36] opened 2019-10-27 09:29 UTC
Hello!
It's sophisticated for me to migrate from cmdswitch to your plugin.
I'm using .sh scripts in state_cmd, on_cmd and off_cmd, for example:

>   "on_cmd": "sudo /home/pi/on.sh MAC on", 
>   "off_cmd":` "sudo /home/pi/off.sh MAC off",
>   "state_cmd": "sudo /home/pi/status.sh MAC | grep -l 'ON'"

Is it possible to link in your `state_cmd` my `on.sh, off.sh and status.sh`?
Probably you can help with solution of my problem.
Thanks in advance,
Maxim.

**Comment by ztalbot2000** [comment] 2019-10-27 12:56
I just got your message.  I should have some time today to have a look.  Please send me your old homebridge .config file, your scripts and what you tried for your new .config file.
I may not need them, but everything may help.

If your worried about privacy, you can send them directly to ztalbot2000@gmail.com

Thanks,
John Talbot

**Comment by profx5015** [comment] 2019-10-27 20:09
Hello!
Attaching config and scripts.



[cmd.zip](https://github.com/ztalbot2000/homebridge-cmd4/files/3776326/cmd.zip)

**Comment by ztalbot2000** [comment] 2019-10-28 01:03
So far I have had only a cursory glance.  First you have no section for
cmd4 in you config.json file.  ie

{

    "bridge": {

        "name": "HomeBridge",

        "username": "AC:22:3B:C3:DE:3E",

        "port": 51826,

        "pin": "222-11-222"

    },

    "accessories": [

        {

            "accessory": "RaspberryPiTemperature",

            "name": "RaspberryPi CPU Temperature"

        },

        {

            "accessory": "RaspberryPi",

            "name": "Raspberry Pi",

            "os": "Raspbian",

            "interval": 5000,

            "showCpuUsage": false,

            "showMemoryUsage": false,

            "showTemperature": true,

            "enableReboot": true

        }

    ],

    "platforms": [

        {

            "platform": "cmdSwitch2",

            "name": "Switches",

            "switches": [

                {

                    "name": "Кипятильник",

                    "on_cmd": "sudo /home/pi/connect.sh C3:95:4E:F4:0F:22
on",

                    "off_cmd": "sudo /home/pi/off.sh C3:95:4E:F4:0F:22 off",

                    "state_cmd": "sudo /home/pi/status.sh C3:95:4E:F4:0F:22
| grep -l 'ON'",

                    "manufacturer": "Redmond",

                    "model": "RK-M171S"

                }

            ]

        },

        {

            "platform": "cmd4",

            "accessories": [

                {

                    "name":         "Кипятильник",

                    "displayName":  "Кипятильник",

                    "type":         "Switch",

                    "manufacturer": "Redmond",

                    "model":        "RK-M171S",

                    "on":           "FALSE",

                    "polling": [

                       {"on":       "FALSE", "interval": 120, "timeout":
4000}

                    ],

                    "state_cmd": "/home/pi/connectCMD4.sh"

                }

            ]

        },

        {

            "platform": "config",

            "name": "Config",

            "name": "Config",

            "port": 4200,

            "sudo": true,

            "temp": "/sys/class/thermal/thermal_zone0/temp",

            "standalone": true,

            "restart": "sudo -n systemctl restart homebridge
homebridge-config-ui-x",

            "log": {

                "method": "systemd",

                "service": "homebridge"

            }

        }

    ]

}
Your config file also mentions three bash shells, one for on, off and
status.  You only sent me two, the third was called auth.sh which is not
the status.sh you specify.
Have a look at the README, there is an example moving to CMD4.  Which by
the way you do not really need to do, unless you want more information
other than on/off/status if your device supports the other characteristics
of a switch.
If you still wish to migrate, hard code in the one on/off/status/....
script the MAC address as it does not need to be passed as you only have
one anyway.  You also do not need sudo if you set the sticky bit of the
script or adding pi to sodu using the visudo command.

If your still stuck, send me the status.sh and I'll try again.

John Talbot



the

**Comment by profx5015** [comment] 2019-10-28 09:16
Sorry, lost the file.
[status.zip](https://github.com/ztalbot2000/homebridge-cmd4/files/3777938/status.zip)

**Comment by ztalbot2000** [comment] 2019-10-29 02:29
This is as far as I got tonight. it does pass shellCheck. I found the off
and on parts within connect.sh.  Interestingly enough, even in cmdswitch2
there is no thing really as a stat_cmd and that is because this does not
exist in the hap spec. By querying anything of a device and if it does not
return, that is essentially the devices status.

You can play with what I have so far.
What bluetooth device are you playing with anyway?  I only ask as If I have
one I can do better testing.

ttfn,
John Talbot

**Comment by profx5015** [comment] 2019-10-29 09:01
> What bluetooth device are you playing with anyway?
It is Redmond SkyKettle RK-M171s

**Comment by ztalbot2000** [comment] 2019-10-29 15:14
I just release version 2.3.0 which will help us by allowing state_cmd_prefix and state_cmd_suffix to be specified.  You can now add your sudo and MAC address as you had it before.
I'm going to close this, but continue to help you as there really is no issue, especially after releasing 2.3.0, The problem is really just how to move your stuff forward and I'll continue to help you with that.

**Closed by ztalbot2000** 2019-10-29 15:14 UTC

**Comment by ztalbot2000** [comment] 2019-10-29 23:31
I looked up this kettle. it is really cool and I can see possibilities of
using Cmnd4. I wonder if you set the type to be a Thermostat, or something
with temperature, can you control that too?
With 2.3.0 that I just released, I made the changes to the files I created
that will help you.  since I don't have the device, you are going to have
to try it yourself.

**Comment by ztalbot2000** [comment] 2019-10-29 23:39
Actually, there is an accessory type called. HeaterCooler that may be
better. ill alter the script file I created to get your kettle temperature.

**Comment by ztalbot2000** [comment] 2019-10-30 00:30
This changes it from Switch to HeaterCooler, where you can query the
temperature.  You could probably set the TargetTemperature, that would be
interesting.
I don't know if IOS likes a HeaterCooler, but Eve might.  Here are the
files for HeaterCooler. they are still untested as I do not have the
device, but you will get the idea.

let me know how you make out. I'm definitely interested.

John Talbot

**Comment by ztalbot2000** [comment] 2019-10-30 00:39
I'm still thinking about this.  if you add in FakeGato history (Available
in Cmd4) you could get a graph of the current temperature !
