### ISSUE TITLE
Compatibility Issues with Homebridge

### ISSUE THREAD

**Issue by jsiegenthaler** [ztalbot2000/homebridge-cmd4#56] opened 2020-06-05 13:56 UTC
Homebridge reports:

[6/5/2020, 15:53:52] The plugin "homebridge-cmd4" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!

Can you fix this?

**Comment by ztalbot2000** [comment] 2020-06-06 15:25
duplicate of #51

**Closed by ztalbot2000** 2020-06-06 15:25 UTC

**Comment by ztalbot2000** [comment] 2021-09-03 15:52
Hi,

   A long time ago, I removed hap-nodejs as a dependancy. As well as homebridge. I'd really like to put hap-nodejs back so that at run-time when I include homebridge/plugin-ui-utils I can check things like format types and ranges, without duplicating this in my current code.  Unfortunately including homebridge/plugin-ui-utils they have no way of accessing _api in server.js to get a run-time way of accessing formats/units ...

 I don't see this as a problem, but I do remember you wanting me to remove this dependancy, which I did at the time.  I was wondering if you had any thoughts on the matter.

Thanks,
John Talbot
ztalbot2000@gmail.com

**Comment by jsiegenthaler** [comment] 2021-09-03 16:23
Hi
Sorry, I do not recall ever asking you to remove a dependency. 
I'm not a hap-nodejs expert by any means, I'm just a small developper with much less skill than you.
So I don't really have any thoughts on this matter at all.

**Comment by ztalbot2000** [comment] 2021-09-03 16:47
Hi,

  Well thanks for replying so quickly.  I appreciate it anyway.

Take care,
John
