### ISSUE TITLE
Speaker no longer supported in iOS 16.x

### ISSUE THREAD

**Issue by Edelheid** [ztalbot2000/homebridge-cmd4#137] opened 2023-01-27 01:12 UTC
Hi,

After upgrading to iOS 16.2 (possibly broken in iOS 16.x) the "Speaker" via CMD4 is being noted as "Not Supported" in the Home app. It also doesn't show up under Speakers & TVs. Is it just me? I haven't made any notable changes to the CMD4 plugin as well as to HB in general before this happened. I should probably note that I am on the new architecture, but I can vaguely recall the "Not Supported" message already being there prior to that change.

Something else I've noticed while trying to troubleshoot is that when adding a new speaker using CMD4, HomeKit adds it to the Default Room, but it's not accessible in the Home app. I have to use a third-party HomeKit app like Controller to navigate the Default Room there and manually move the speaker accessory to a different, actual room. The Default Room is hidden in the Home app when there's no accessories in there, but in this case it's probably hidden due to the "Not Supported" issue.

But, still on the subject of third-party HomeKit apps, interestingly Controller still recognizes the accessory as a speaker and functions seem to be available there which might make this a Home app problem. I don't have an actual AirPlay speaker that shows up natively in the Home app to verify if all speakers are affected and not just this plugin.

**Comment by ztalbot2000** [comment] 2023-01-27 01:22
Hi,

   I have not done anything to Cmd4 in a while that might cause this. That
is not to say that either IOS or Homebridge might have. Could you please
send me your config.json so I can poke around with it.

Thanks,
John

**Comment by Edelheid** [comment] 2023-01-27 04:04
Sure thing. Here it is:

`{
    "bridge": {
        "name": "Homebridge 86CB",
        "username": "EE:45:CE:39:30:E5",
        "port": 514455,
        "pin": "198-52-893",
        "advertiser": "avahi",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [
            {
               "type":                     "IrrigationSystem",
               "displayName":              "My_IrrigationSystem",
               "active":                   "ACTIVE",
               "programMode":              "PROGRAM_SCHEDULED",
               "inUse":                    "IN_USE",
               "remainingDuration":         60,
               "statusFault":              "NO_FAULT",
               "name":                     "My_IrrigationSystem",
               "manufacturer":             "Somebody",
               "model":                    "Anything",
               "serialNumber":             "12345",
               "stateChangeResponseTime":   3
            },
            {
               "type":                     "Speaker",
               "displayName":              "My_Speaker",
               "mute":                     "FALSE",
               "volume":                    5,
               "name":                     "My_Speaker",
               "manufacturer":             "Somebody",
               "model":                    "Anything",
               "serialNumber":             "12345",
               "stateChangeResponseTime":   3
            },
            {
               "type":                     "LockMechanism",
               "displayName":              "My_LockMechanism",
               "lockCurrentState":         "UNSECURED",
               "lockTargetState":          "UNSECURED",
               "name":                     "My_LockMechanism",
               "manufacturer":             "Somebody",
               "model":                    "Anything",
               "serialNumber":             "12345",
               "stateChangeResponseTime":   3
            }
            ]
        }
    ]
}`

**Comment by ztalbot2000** [comment] 2023-01-29 12:27
Hi,

   So more investigation will be required.  
First the config.json you gave is incomplete as it has no platform, polling or state_cmd, so I had to improvise. This is what I used:
"platforms": [
        {
            "platform": "Cmd4",
            "name": "Cmd4",
            "debug": true,
            "statusMsg": true,
            "timeout": 5000,
            "accessories": [
                {
                   "type": "Speaker",
                   "displayName": "My_Speaker",
                   "mute": "FALSE",
                   "volume": 5,
                   "name": "My_Speaker",
                   "manufacturer": "Somebody",
                   "model": "Anything",
                   "serialNumber": "12345",
                    "state_cmd": ".homebridge/Cmd4Scripts/State.js",
                   "interval": 5000,
                   "polling": [
                       {
                           "characteristic": "volume"
                       },
                       {
                           "characteristic": "mute"
                       }
                   ]
                }
            ]
        }
]

There are some oddities. HomeKit no longer likes "_" underscores in names, saying that it's an emoji.
I require more investigation because HomeKit now gives the message, "This accessory has not been certified to work with HomeKit so some features may not be available".
Most likely this is a problem with HomeBridge, specifically hap-nodejs. Keep an eye out for updates to those which might suddenly fix the problem. I'll try to keep you updated on what I find.

**Comment by ztalbot2000** [comment] 2023-01-29 20:49
I'm still investigating. Seems a lot of people are having issues with their plugins. For example: https://github.com/homebridge/homebridge/issues/2553
The solution is supposedly making the accessory be published externally from the bridge and setting the appropriate category. Cmd4 has this capability. Add to your config.json for the speaker:
"publishExternally": true,
"category": "Speaker",

that being said, I still have had no luck and will keep investigating. If you want to try, you're welcome to.

ttyl,
John

**Comment by Edelheid** [comment] 2023-01-31 01:04
Yes, sadly it doesn't work on my end either. Trying to add it as a separate accessory when published externally, the Home app seems to recognize it to be a speaker there, but once added it's "Not Supported". Thanks for looking into this John! I'll also add any potentially useful info here if I come across them.

**Comment by ztalbot2000** [comment] 2023-01-31 01:12
I thought I'd update you on my progress.  I tried the example homebridge-independent-platform-plugin. It gave me lots of problems as we are seeing in Cmd4 but I did get it going. I don't have time to try it with CMD4 tonight but the publishExternally is the right thing to do, as mentioned above.  How I got the example to work was that you must add the accessory again. The first time from the bridge, the second time the home app shows the accessory to be added externally.  I'll detail this later, but it seems it is possible.

John

**Comment by ztalbot2000** [comment] 2023-01-31 22:05
I changed the home bridge-independent-platform-plugin that I got working as a publishedExternally accessory from Switch to Speaker. It no longer works giving the same, "Not supported" message.
I put a ticket into homebridge . See https://github.com/homebridge/homebridge/issues/3313
Since the ticket I put in refers to their example independent platform plugin code when changed from a Switch to a Speaker then it is more likely they will look into their own issues. 
I'll keep you posted.
Thanks for giving it a try yourself by the way!

John

**Comment by ztalbot2000** [comment] 2023-02-01 01:02
I got a response from Homebridge. They said, "You’ll have to file this bug report with Apple. Home only supports a Speaker service as part of a video doorbell accessory. You will be able to see it in other HomeKit apps, like Eve."
I never asked what kind of Speaker you actually have. Homebridge also supports a SmartSpeaker and TelevisionSpeaker. I'm wondering if they could be your solution.

**Comment by ztalbot2000** [comment] 2023-02-02 20:35
I tried a SmartSpeaker and a TelevisionSpeaker. The TelevisionSpeaker gave the same result as a Speaker. The SmartSpeaker does not give Mute and volume control, just a play button.
I'm sorry to say that the problem is with Apple and since they changed their Home GUI behaviour, there is nothing I can do about it. You can try Eve like Homebridge mentioned.  With that I can only close the issue as the problem is not under our control.

John

**Closed by ztalbot2000** 2023-02-02 20:35 UTC

**Comment by ztalbot2000** [comment] 2023-02-25 11:57
Hi,

  Thanks for not shooting the messenger.  Apple has done that to me a few
times, not only in HomeKit but their IOS API's for apps that I wrote. Don't
even get me started on swift which is anything but.
   Did you try Eve by the way?

Ttyl,
John

**Comment by ztalbot2000** [comment] 2023-02-28 01:15
Hi,

  It seems Apple removed the Speaker functionality and added the
smartSpeaker play functionality; While Eve has the old Speaker
functionality but not the new SmartSpeaker play button.  We just can't win!
   I agree though that it would be ideal if it were just in HomeKit.
Let me try making a Speaker an extension of a SmartDoorBell and see what it
looks like and behaves.
  The category is supposed to be a hint to Apples FUI on what it looks
like.  It may be part of the solution if we can make a doorbell or a switch
look like and behave like your old Speaker.

  I'll get back to you.

John

**Comment by ztalbot2000** [comment] 2023-03-01 21:59
Hi,

  So I tried three ideas.
A switch with a linked accessory of a Speaker - only showed Switch On/Off
controls
{
   "type": "Switch",
   "displayName": "xDoorbelTRY",
   "on": false,
   "name": "xDoorbelltry",
   "publishExternally" : true,
   "linkedTypes":
   [ {
      "type": "Speaker",
      "displayName": "SPEAKER",
      "category": "Speaker",
      "mute": "FALSE",
      "volume": 0
     }
   ]
},
A switch with a category of a Speaker - only showed Switch On/OFf controls
{
   "type": "Switch",
   "displayName": "xxDoorbelTRY",
   "category": "Speaker",
   "on": false,
   "name": "xxDoorbelltry",
   "publishExternally" : true,
   "mute": "FALSE",
   "volume": 0
},
A microphone with Category of a Speaker. - Microphone now also gives
unsupported like that of a Speaker
{
   "type": "Microphone",
   "displayName": "aaDoorbelTRY",
   "category": "Speaker",
   "on": false,
   "name": "aaDoorbelltry",
   "publishExternally": true,
   "mute": "FALSE",
   "volume": 0
},

So unfortunately I do not have a solution to get around the changes that
Apple made.  If I think of anything else, I'll let you know.
