### ISSUE TITLE
[Feature Request] Create Child Bridge in Homebridge v1.3.0

### ISSUE THREAD

**Issue by mitch7391** [ztalbot2000/homebridge-cmd4#91] opened 2021-02-21 07:18 UTC
**Describe The Bug:**

Once Homebridge is updated to `v1.3.0` there is the ability to separate each plug-in as its own child bridge. It appears that cmd4 is not able to take advantage of that function.

**To Reproduce:**

1. Update Homebridge to `v1.3.0`.
2. Open plug-ins tab in config-ui-x.
3. Click the little spanner icon.
4. Click 'Bridge Settings'.

**Expected Behaviour:**

An option should appear to select the child bridge and restart homebridge. Upon going back into these settings there will be an individual QR code for the plug-in to be its own bridge.

**Screenshots:**

![image](https://user-images.githubusercontent.com/40288237/108618247-7cd14b80-7457-11eb-8aaa-07f4bf5374cb.png)

**Environment:**

* **Node.js Version**: v14.15.5
* **NPM Version**: v7.5.4
* **Homebridge Version**: v1.3.0
* **homebridge-cmd4 Version**: v3.1.3
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by ztalbot2000** [comment] 2021-02-21 21:24
Hey Mitch,

   Is this a new feature?  Could you do this in 2.4.2?
I think you might still be able to do this in 3.0 but you would have to
define the devices as standalone accessories, compared to platform
plugins.  It is possible that you cannot restart a platform plugin but you
can restart a standalone accessory.

In order to get that TV icon, Cmd4 had to change to platforms. It is
possible that the change means this difference. I have to do a bit of
research, but I believe this to be the case.  It makes sense.

I think I documented how to do this somewhere, I can't find it at the
moment and I'm so far behind on a lot of things. It may be in some of the
discussions I had about the TV icon not showing up. You could change over
your config.json, but you would lose the TV icon and caching; All benefits
of platform plugins.

I'll leave this open for now.  This is what I believe the issue is though.

**Comment by mitch7391** [comment] 2021-02-22 01:53
Hey John, maybe I should have raised this as a feature request then as you could not do this in previous versions of cmd4. This is a brand new feature of Homebridge and is different to HomeKit requires TVs to be its own bridge.

In the latest version of homebridge you can make each individual plug-in its own separate child bridge. I think the benefits here are if own particular plug-in was slowing down the rest of your homebridge then it will now only slow down that child bridge; also probably more reliability benefits too.

I believe cmd4 right now does not get the option to activate it through homebridge due to not having a schema set up or some plug-ins let you directly edit your plug-ins section of the `config.json`; normally either of these options for config editing appear in the screenshot I have attached above. Hope this makes more sense :)

**Comment by ztalbot2000** [comment] 2021-02-22 02:07
Hi Mitch,

I hope it does not have anything to do with a config.schéma.  I had started
on it, but it's really tough.

Until I figure out if Standalone/Platform is the correct answer, we can
leave it as a bug.

I'm actually working on a bigger issue.  There is a lot of nasty code
trying to undo stored Cmd4 Designations, keeping the changed
characteristics.  Instead I'm just saving the characteristic states, so I
don't have to parse out things like fetch, state_cmd ...  The changes
require some new unit testing techniques, but make things so less
complicated and a lot cleaner code. I've also noticed cached values work so
much better. I believe in some cases they were not being kept over restarts.

TTFN,
John

**Comment by mitch7391** [comment] 2021-02-22 02:15
I am hoping it is just the fact that you have the schema setup that it allows you to access it; just an observation.

Here is information on child bridges:
https://github.com/homebridge/homebridge/wiki/Child-Bridges

> I believe in some cases they were not being kept over restarts.

This sounds like why my aircon turns off when I restart homebridge; it has been low on my list to raise with you haha but sounds related!

**Comment by oznu** [comment] 2021-02-23 05:26
I've adjusted the script the Homebridge UI uses to extract the "alias" to handle the edge case I found in cmd4. It will now show you the plugin-specific plugin editor as well as the child bridge configuration screen.

This will only work for CMD "platform" config types, not "accessory" config types, as the UI only handles a plugin exposing one type of integration.

**Comment by mitch7391** [comment] 2021-02-23 05:35
Oh nice work @oznu, testing it out now :) looks like you are doing the rounds making sure the new functionality is working!

**Comment by ztalbot2000** [comment] 2021-02-23 05:49
I have found the issue with not keeping the correct status over restarts.
It is the in the change I was telling you about.  I was just about to put
out the release and am investigating something that seems a little fishy.

TTFN,
John

**Comment by ztalbot2000** [comment] 2021-02-23 06:03
I believe this issue is not related to 3.0.  I'm pretty sure that it was in
2.4.2

**Comment by ztalbot2000** [comment] 2021-02-23 07:55
Hey Mitch,

  I just released 3.2.0.  All your caching issues should disappear as well
as your air conditioner staying on.

**Comment by mitch7391** [comment] 2021-02-23 08:08
Hey John, looks like the issue has been resolved with restarts :) there are still a couple of other niggly bugs I will raise later as separate issues, but I will leave you to focus on your main work first.

**Comment by mitch7391** [comment] 2021-02-23 08:13
Actually I may have spoken too soon, with a normal restart from the main web UI there no issue and my aircon stays on; however when I did a restart from the UI Homebridge settings page (like as required when setting debug mode) it turned off my aircon as it restarted Homebridge...

**Comment by ztalbot2000** [comment] 2021-02-23 15:01
I'm getting such headaches lately from Homebridge-UI.  I have spent so much
time automating test cases, but cannot account for what they do. which of
course, should be no different. If however they call API's that refresh old
or original state, what can I do?

Can you please try to make sure that it works as expected without the UI so
I can then determine where to look.

Thanks,
John

**Comment by mitch7391** [comment] 2021-02-24 01:20
No worries John, I will do some testing tonight after work.

**Comment by ztalbot2000** [comment] 2021-02-24 01:22
Hi Mitch,

  I got a few things out of the way and was just about to try an air
conditioner and see what happens.

ttfn,
John

**Comment by mitch7391** [comment] 2021-02-24 01:25
I swear you don’t sleep John haha I will still give it a go myself tonight too, keen to hear your results.

**Comment by ztalbot2000** [comment] 2021-02-24 02:02
Just putting together an environment.  Is their any chance in the IOS Home
app you have turn device off when you leave the room set to true?   Just
another setting to worry about and it's not even mine.

ttfn,
John

**Comment by ztalbot2000** [comment] 2021-02-24 02:08
I also just noticed in my current test setup where fetch is "Polled" and
only currentHeatingCoolingState is set in polling.  The result being that
when changing the state, targetHeatingCoolingState (cached) gets set, but
of course currentHeatingCoolingState is fetched from the device, hence a
mismatch.  This is really not my fault as it's a config issue, but also one
I thought I may have handled with at least a warning.

TTFN,
John

**Comment by mitch7391** [comment] 2021-02-24 02:38
> Just putting together an environment.  Is their any chance in the IOS Home
app you have turn device off when you leave the room set to true?

I am not sure what you mean here sorry John.

> The result being that
when changing the state, targetHeatingCoolingState (cached) gets set, but
of course currentHeatingCoolingState is fetched from the device, hence a
mismatch.

Could this account for the “null” reading I am getting? It seems for me it only receives that value when I ‘set’ and it grabs an instant ‘get’ afterwards; which always returns “null”.

**Comment by ztalbot2000** [comment] 2021-02-24 02:45
Not the null.  That one I proved is yours.  Sorry.

The one I'm talking about is a mismatch of when you only define polling for
currentHeatingTargetState and not targetHeatingCoolingState and you have
fetch set to "Polled".

As it turns out I did not put a check to warn the user if they did this.
At least now I can do the unit testing for this type of thing and not have
to worry about it again.

TTFN,
John

**Comment by mitch7391** [comment] 2021-02-24 02:51
> Not the null.  That one I proved is yours.  Sorry.

Damn, I keep being hopeful it is not caused by me haha this “null” problem has been driving me up the wall...

> At least now I can do the unit testing for this type of thing and not have
to worry about it again.

Nice job :)

**Comment by ztalbot2000** [comment] 2021-02-24 22:06
Hey Mitch,

I certainly can understand.

I just released 3.2.1.  I don't think it will affect you.  It basically
will generate a warning if fetch is Polled and you only poll for a
characteristic that is a Target type characteristic and not it's Current*
type characteristic.

I finished my testing on restarts that might turn your devices off over a
restart.  It doesn't, but I did notice that HomeKit will resend the
TargetHeatingCoolingState of the previous value.  For example, if it was
set to Heat, it will resend the Heat command.  If by chance your script
turns off the device and back on in that scenario, that could be your
issue. Not the null but the on/off.

The Cmd4 code is getting a lot cleaner.  I'm actually kind of happy with
how it looks at the moment.  Especially now that I can actually test even
the console logs of Cmd4 for expected behavior.

TTFN,
John

**Comment by ztalbot2000** [comment] 2021-02-25 02:15
Hey Mitch,

  I think this thread got off topic.  That's what happens when I reply via GMail.
Anyway, I finally got a round to looking into this one.  You are right that to do this automatically, I need a config.schéma file, which is addressed in the already existing feature request of being homebridge verified.
So I will close this in favor of the original request and to keep my issues low.
The Homebridge-config-UI-x says you can do this by creating the bridge names yourself.  It seems like this is really just a hack to get multiple instances of Homebridge running at the same time.

'anyway, I'll tag this as duplicate and close it.

**Closed by ztalbot2000** 2021-02-25 02:15 UTC
Labels: bug

**Comment by mitch7391** [comment] 2021-02-25 11:31
@oznu might be quicker to just ask you here. What is the difference (the actual command issued) between these two types of restarts?
![image](https://user-images.githubusercontent.com/40288237/109146917-61d84180-779f-11eb-9cb1-ee2a9803966d.png)

I do not think John uses config-ui-x and knowing the difference between the two restarts types might help him sort out an issue with my accessories setting to 'off' when homebridge restarts from the 'restart required button', but has no issue with the normal restart button.

**Comment by ztalbot2000** [comment] 2021-02-25 15:03
Hey Mitch,

  Your issue may not be yours or mine.  I was just looking at HomeBridge
issues and it seems their may be somethings already reported that seem
similar.

ttfn,
John

**Comment by mitch7391** [comment] 2021-02-25 21:04
Hey John, do you have a link to the issue for me? I had a quick browse and didn’t see anything obvious.

**Comment by ztalbot2000** [comment] 2021-02-26 01:17
https://github.com/homebridge/homebridge/issues/2825

That is the one I saw. I wonder how your testing would go if you tried
older versions of Homebridge.  Just another thought.

TTFN,
John

**Comment by mitch7391** [comment] 2021-02-26 01:44
I thought that might be the one you were talking about but I think that is a completely different issue as I am not losing my accessories or associated automations...
